= Draft

_Ниже речь про содержанок_

-- Почему некоторые женщины согласны на такую жизнь? Я не такая, но от осознания, что другие так живут, мне тошно.

-- Ну… Я могу только предполагать, вернее могу попробовать сгенерировать вам несколько вариантов. Когда я был в вашем возрасте я тоже недоумевал с некоторых поступков людей. 

-- Теперь вы их понимаете лучше? 

-- Не могу сказать что я могу ответить на вопрос “почему кто-то что-то сделал”, но теперь я охотно верю, что у них действительно есть мотивы, и что самое важное, они в них искренне верят, независимо от того, насколько те ошибочны. 

-- И как вы к этому пришли?

-- Скажите, у вас были трудные ситуации в жизни?

-- Нууу…

-- Нет, хлопоты связаны с поступление в колледж и что ваш парень вечно дарит вам тюльпаны не того цвета - не в счет. Я про трудности которые надламывают саму вашу суть, заставляют посмотреть на мир под другим углом, зачастую под более недоверчивым…

-- Нет, таких наверное еще не было, -- Мейв пожала плечами.

-- Когда я впервые столкнулся с такой ситуаций, то многое понял. В юношестве я думал о самоубийстве как о чем-то дурном, нелогичном, идущим против самой природой. Но в тот момент… Нет, я не был на грани самоубийства, -- поспешил он успокоить Мейв, которая опустила бокал пива и огромными, полными страха, глазами уставилась на собеседника. -- Но я понял обстоятельства при которых я на этой грани окажусь. 

-- И?.. При каких? -- Мейв была заинтригована и явно не довольна сделанной Маркусом паузой. 

-- Я не знаю как это описать, это нужно прочувствовать. Когда мы в нормальном состоянии мы позитивнее смотрим на мир… –- он слегка улыбнулся. -- Я пытаюсь сформулировать для вас мысль, и мой мозг как будто бы не хочет этого делать, потому что: “Да это бред какой-то, ты же в это не веришь? правда?”.

-- Ну… Вы говорите как получается, мне сейчас грустно, и я довольно восприимчивый человек, так что могу проникнуться.

-- Когда тебе плохо, по настоящему плохо… Когда любые виды развлечений лишь ненадолго отвлекают тебя от неизбежного… Где бы и с кем бы ты ни был, всегда наступает момент когда ты опять окажешься наедине с собой, с собой которому плохо… -- несколько мгновений Маркус молчал, погрузившись в свои воспоминания. -- И в довесок к проблемам которые окунули тебя в это состояние, добавляется проблема того, что когда наедине с собой тебе плохо, единственный человек который может помочь - это ты сам… а тебе плохо… а когда тебе плохо ты не хочешь никому помогать, ты хочешь чтобы тебя оставили в покое, дали отдохнуть… Проходят недели, иногда месяцы, а ты все хочешь чтобы тебе дали отдохнуть... хотя тебя никто особо и не напрягал… просто жить обычной жизнью в тот момент - уже сложно…

-- И никто действительно не может помочь?.. - едва слышно спросила Мейв.

-- В этот момент ты задаешься вопросом: “а зачем тогда это все?” -- Макрус уже не слышал ничего вокруг. -- И видимо это то дно от которого можно слегка оттолкнуться. Ты пугаешься, понимаешь что так дальше нельзя, начинаешь искать позитивные моменты ради которых стоит жить… у кого-то это семья, у кого-то желание продолжать получать плотские удовольствия, у кого-то банальный страх смерти… Они становятся лестницей по которой ты начинаешь свой путь наверх… Но что будет если в этот момент она сломается? 

-- Думаете у самоубийц она сломалась? 

-- Да, и они не нашли других. Они всегда есть, просто некоторые задыхаются раньше, чем найдут…

-- Я рада что вы нашли! - утирая слезы прохрипела Мейв.

-- Возможно для тех женщин такая жизнь это своеобразная лестница. Не высокая, не позволяющая полностью вынырнуть, но другую они не нашли, или найти не в состоянии. 

-- Мне кажется они и не ищут…

-- Возможно, но тут уже в дело вступает рыночная экономика, не было бы спроса, пришлось бы начать что-то менять, или задохнуться.  
