== Глава

Пронизывающий звук наполнил комнату погруженную в полумрак.
Макс лихорадочно пытался нащупать источник раздражения роняя руку на прикроватную тумбочку.
Наконец ладонь встретилась с чем-то похожим на стационарный телефон.

-- Доброе утро! Вы просили разбудить вас перед завтраком, в 8 вас будут ждать в баре на втором этаже.

-- Спасибо! -- прохрипел Макс в трубку издающую короткие гудки. 

Протирая глаза он наконец начинал вспоминать где находится. 
За окном на горизонте раскинулся горный хребет за которым начал слегка проявляться огненный круг солнца. 
Отель, в который он прибыл накануне вечером, так же находился на возвышенности, так что ослабший от дороги Макс предпочел закончить уходящий день в баре вместо разведывательной прогулки по окрестностям. 
Там он встретил несколько единомышленников и сейчас ощущал последствия продуктивного общения в виде шума в голове и легкой тошноты.

Бар на втором этаже представлял из себя узкое помещение с длиннющей барной стойкой и несколькими столиками вдоль противоположной стены, которые к момент прихода Макса были уже заняты.
Из присутствующих он узнал только одну светловолосую девушку, которая попыталась избежать встречи взглядов, так что Макс решил присесть за соседний стол к молодой паре.

-- Можно? 

Парень одобрительно кивнул и продолжил поглощать свой бифштекс, а девушка с легкой улыбкой продолжала смотреть на Макса все время что он усаживался за стол, и не особо смутилась при встрече взглядов.
"Никогда не понимал, как воспринимать такие затяжные созерцания от занятых женщин", подумал он про себя и на  всякий случай поправил прическу.

-- Я Иви, а это Раян, -- очень энергично выпалила новая соседка по столику.

-- Очень приятно! Макс!

-- Вы тоже будете участвовать в квесте? -- не забавляя энтузиазма продолжила Иви.

-- Да, я так понимаю здесь сбор всех участников, -- Макс обвел взглядом присутствующих.

-- А я вот думаю, что он уже начался...

"Архимед был явно менее воодушевлен своими открытиями", проскочило в голове Макса при виде горящих глаз собеседницы.

-- Вот, взгляните на их меню, -- она указала на название блюд выполненных в виде ребусов из рисунков сильно напоминающих египетские иероглифы. 
-- Раян на самом деле думал что заказывает бефстроганов, но видимо мы что-то напутали, -- радость на ее лице сменилась наигранной грустью.

-- Главное, что тут есть мясо, -- прокомментировал басовитым голосом парень, на секунду оторвавшись от блюда.

В этот момент входная дверь слегка скрипнула, чем привлекла к себе внимание присутствующих. 
В помещение уверенным шагом вошла женщина в строгом деловом костюме.
За ней мелкими шагами семенил мужчина в возрасте, а закрывала процессию молодая девушка в белом врачебном халате.

-- Всех рада приветствовать! -- Женщина зашла за барную стойку и оперлась на нее руками. 
-- Меня зовут миссис Олди и я отвечаю за то, чтобы вы получили максимальное качество услуг во время данного мероприятия. 

Ее командный голос вызывал у Макса ощущение того, что они сидят в окопе, нежели в баре, и командир вот-вот отправит их на штурм вражеских позиций.  

-- Обычно я предпочитаю знакомиться с нашими гостям лично, но вчера, к сожалению, были личные не предвиденные обстоятельства, -- тем временем миссис Олди продолжала чеканить слова. --
Но я думаю мы с вами еще успеем наверстать упущенное, а пока я хотела бы быстро напомнить вам наши основные правила и дать несколько рекомендаций.
Первое -- хотя победитель в нашем квесте только один, для того чтобы его пройти вам нужно действовать как команда...

-- Мы же правда не в армию попали? -- прошептал Макс соседям по столику. 
Они оба пожали плечами, давая понять что тон ораторши других ассоциаций не вызывает. 

-- Второе -- большинство испытаний которые вам предстоит преодолеть сопряжены с определенными физическими нагрузками, поэтому мы просим вас пройти минимальный медосмотр. 
С чем нам любезно согласилась помочь мисс Тернер, -- она указала рукой на вошедшую с ней девушку. 
-- Если у вас есть какие-то недуги или пожелания, мы обязательно постараемся их учесть. 

-- А что если у кого-то из нас есть несовместимые противопоказания? -- прозвучало с соседнего столика.
-- Отправите нас домой? Почему нельзя было сделать этого до нашего визита сюда?

Миссис Олди несколько секунд сверлила взглядом осмелевшую перебить ее девушку, но затем, добавив еще большой жесткости своему голосу, все таки ответила:

-- Мисс Бартон, как я уже сказала, мы учтем особенности каждого из вас. 
Следующую неделю я лично отвечаю за вашу сохранность и хочу быть уверена в достоверности информации о состоянии вашего здоровья.
Вы все достаточно юны, имеете по 2 ноги и руки, все остальное -- решаемо. -- Она опять сделала паузу и обвела каждого свирепым взглядом, давай понять что дальнейшие вопросы излишни. 

-- Третье -- на протяжении всего квеста мы ведем видео запись происходящего и передаем эти материал в наш местный институт психологии и социологии, -- в этот раз ее рука указала на стоящего рядом мужчину. 
Тот слегка поклонился в знак приветствия.

-- Простите, но я не давал согласия быть подопытным кроликом, -- обратился к ней Раян прилично повысив тон.

Сидевший за самым дальним столиком парень в очках и зализанной прической фыркнул и закатил глаза.

-- Боюсь вас расстроить, мистер Стивенсон, но давали, -- впервые с момента начала разговора на лице миссис Олди появилась улыбка.
-- Этот пункт указан в нашем пользовательском соглашении, которое вы подписываете при приобретении сертификата на участие. 

-- Так и от почки можно отказаться, -- ехидно прокомментировал парень в очках. 

"Или это сделают за тебя твои друзья...". 

-- Шибко умный? -- Раян слегка привстал из-за стола. Макс тоже слегка отодвинулся, готовясь разнимать эту парочку. 
-- По тебе заметно, что кроме чтения бумажек тебя в этой жизни ничего больше не интересует...

-- Господа! -- В этот раз миссис Олди уже пришлось прибегнуть к крику. -- Прошу уважительно относиться друг к другу. 

-- Милый, успокойся, я не вижу ничего страшного в том, что нас буду снимать на камеру, -- Иви взяла его за руку и постаралась усадить назад. -- Мы же сможем потом получить это видео на память? 

Миссис Олди переглянулась с представителем института.

-- Если никто из участников не будет возражать, то думаю мы сможем такое организовать. 
Мистер Стивенсон, мы гарантируем максимальную защиту данных которые сохраняет у себя институт, а также уверяю вас, что процесс съемки никак не отразится на качестве вашего отдыха.

Раяну явно было все равно на озвученные доводы, но под молящим взглядом Иви он все же сел и постарался успокоиться.

-- Так же хочу добавить, что именно сотрудничество с институтом позволяет нам организовать для участников вознаграждение за победу.

-- Тут есть приз?! -- На этот раз удивление уже постигло Макса, но озвучил он его только шепотом для Иви и Раяна.

-- Ну да, 10 штук баксов! Я думала большинство только ради этого сюда и приехали, -- Иви была не менее удивленна вопросом Макса, чем он сам наличием вознаграждения. 

-- Четвертое, -- продолжила миссис Олди смиряя Макса взглядом, -- и последнее.
Приз заберет тот, кто наберет больше всего баллов, но только в случае выполнения всех заданий.
А для этого, напомню, нужно действовать как команда.
Чем больше пользы вы принесете, тем больше баллов заработаете. 
Как мы будем их начислять мы вам конечно же не скажем, импровизируйте! -- На ее лице появилась ехидная улыбка.
-- Желаю вам удачи и надеюсь следующие несколько дней станут самыми незабываемыми в вашей жизни.

Парень в очках зааплодировал, но остановился найдя на себе странные взгляды вместо поддержки.

-- Мис Тернер будет ждать в 103-й комнате, -- кинула напоследок миссис Олди выходя из бара.


