== Глава

Комната 103 была обычным гостиничным номером переделанным под медпункт. 
Белоснежно белые стены, мебель, оборудование и халат на мис Тернер.
Будь она не такой загорелой, вполне могла посоревноваться с хамелеоном.

-- Максим?

-- Да-да, -- Макс слегка покраснел осознав, что просто молча смотрел на медсестру с момента как вошел.
-- Простите... подумал что умер, когда зашел в эту комнату.

-- Раздевайтесь по пояс и ложитесь на кушетку, -- она оставила его слова без внимания и принялась подключать электроды для снятия ЭКГ. Сделав замеры она попросила Макса присесть несколько раз и затем повторила процедуру. -- Удовлетворительно. 

Следующие несколько минут она вносила данные в компьютер, видимо давая Максу время окончательно прийти в себя после приседаний. Следующим этапом был стетоскоп, прикосновение которого к месту недавнего удара заставила Макса вздрогнуть.

-- Давно это у вас с лопаткой? 

-- Уже больше недели, что-то серьезное? 

-- Не думаю, но... -- она с улыбкой глянула ему в глаза возвращаясь за стол, -- обещать, что до свадьбы заживает - не осмелюсь. 

Макс на мгновение утратил возможность дышать. 
"Ох мис Тернер, кажется самое время повторить экг...
Черт возьми, Макс, тебе бы ответ придумывать, а не монологи в голове устраивать.
Ответ-то есть, но стоит ли его озвучивать?
Может это просто проходная шутка..."

-- На что-то намекаете? 

"Лучше бы уже про экг сказал...".

-- Хах, нууу... выйти замуж в этой комнате мне еще не предлагали! -- ее улыбка стала чуть шире.

-- А что предлагали?

"Это еще что было?.."

-- Действительно хотите знать? -- она покосилась на кушетку, но сперва Макс успел уловить удивление на ее лице.

"А что я, простите, ожидал в ответ?.."

-- Нет, как и не хочу звать вас замуж... Но был бы не прочь с вами отужинать!

-- "Отужинать" -- она в голос рассмеялась. -- Да вы оказывается дерзкий аристократ... Боюсь, вынуждена вам отказать, я не имею права заводить отношения с клиентами фирмы. 

"А зачем тогда все эти милые улыбки и странные фразочки?.."

-- Хорошо, давайте после.

Мис Тернер опустила глаза вниз, а потом очень грустно посмотрела на Макса:

-- Все еще нет.

-- И даже откажитесь от ужина с победителем? -- Настырность заставила ее снова улыбнуться.

-- А не сильно ли много достанется победителю? И денежный приз, и ужин со мной? 

-- Хорошо, будете утешительным призом для второго места! -- Максу казалось, что он уже не может перестать штамповать варианты, иначе его мозг просто сгорит от количества кислорода вбрасываемым сердцем. 

-- Это... слегка оскорбительно...

-- Вовсе нет, в заданных условиях занять второе место куда более сложная задача, чем победить.
Мы не знаем точных правил начисления очков, то есть надо не просто быть лучше во всем.
Нужно понять критерии организаторов, постоянно оценивать кто по ним побеждает, и быть на шаг позади. 
Куда больше мороки, не находите?

-- И вы действительно согласны потратить больше усилий, чтобы получить не 10 штук баксов, а ужин со мной? 
Это всего лишь ужин, я ничего больше не обещаю.
А даже если бы и обещала, в современном мире на 10 штук можно получить куда больше удовольствия.

"Потому я и назвал этот приз утешительным..."

-- Я ехал сюда ничего не подозревая о призе за победу, так что можно сказать, я ничего не теряю.

-- Боюсь про меня вы тоже не подозревали, так что не засчитано.

"А ты хороша..."

...

-- Так и не спросил как вас зовут? -- уже открывая дверь спросил Макс.

-- Сегунда, -- она скорчила нарочито искусственную улыбку. 

-- Мне кажется "Королева шипов" подошло бы лучше... -- покачивая головой и улыбаясь он вышел в коридор.