== Глава

Макс проснулся от того что кто-то тряс его за плечи. 
Он приоткрыл глаза, но тут же зажмурил их от яркого дневного света.
Щурясь он разглядел напряженное лицо Раяна на фоне синего неба, на горизонте со всех сторон виднелись горы от которых его отделял густой лес.
Чуть прийдя в себя Макс разглядел всех кого видел на завтраке. 

-- Где мы? -- похрипел он все еще сонным голосом, отчаянно пытаясь вспомнить где засыпал. 
-- И что за хрень у тебя на руке? 

-- Ни одного тебя волнуют эти вопросы. -- ухмыльнулась Иви, кивком головы указывая на руку Макса.

Он медленно опустил глаза на левое запястье и увидел там массивный железный браслет плотно облегающий руку.
Макс слегка повернул предплечье и увидел небольшой циферблат отсчитывающий время: "11:37:19". 
Он машинально попробовал его снять, но Раян его остановил. 

-- Я уже пробовал, только хуже сделаешь.

-- Ну что ж, начало впечатляет...

-- Что в твоем рюкзаке? -- реплика осталась без внимания.

Макс осмотрел окружающих, видимо оный имелся у каждого.

-- Ноутбук... похоже полностью разряженный. Что у вас?

-- У кого-то еда, у кого-то карта, -- Раян начал отвечать за всех, явно считая себя лидером группы.
-- У кого-то веревки и карабины, короче всего по не многу.

-- А у меня вот это, -- парень в очках показал на небольшой сверток бумаги. 
-- Похоже на вступительное слово, теперь когда все очнулись можем ознакомиться.

-- С каждого по возможностям... -- пробормотал Раян. -- Давай, Эди, жги.

-- Дамы и господа, -- начал декламировать Эди. 
-- Как вы уже могли догадаться, ваше приключение началось. 
Впереди у вас много интересных заданий, и лишний раз напомню, что справится с ними вы сможете действуя только как команда.
Но и про личный приз забывать не стоит, чем больше вы помогаете команде, тем выше ваши шансы.
-- Эди прочистил горло.
-- Думаю все уже обратили внимание на свои запястья. 
На ближайшие дни в этом браслете заключена ваша жизнь. 
Батарею питает электромагнит сдерживающий иглу со смертоносным ядом...

Присутствующие переглянулись пытаясь найти поддержку в собственном скепсисе в глазах других.
А Эди тем временем продолжал.

-- ... циферблат показывает время до разряда. 
Доведете до нуля - вы труп.
Попробуете избавиться от браслета - вы труп. 
Попробуете сломать... ну вы поняли...

-- К чему весь этот цирк? -- Раян закатил глаза от услышанного. 
-- Сказали бы что мы ограничены по времени да и все.

-- Как показывает практика, кто-то из группы обязательно будет не доволен создаваемым антуражем...
-- Эди закончив читать предложение расплываясь в улыбке глянул на Раяна. 
Тот резко изменился в лице, как буд-то его публично пристыдили. 
-- ... Это его право, но надеюсь среди вас найдутся и любители полного погружения.
-- Эди кивнул сам себе. 
-- Как уже было сказано, доводить таймер до нуля нежелательно, так что вам нужно будет раздобыть новую партию батареек.
Первая локация с ними отмечена на карте.
Желаем удачи! 

-- Отлично, не будем затягивать, где там карта? -- Раян потянулся к Иви.

-- Может мы сначала познакомимся? -- Макс обвел взглядом окружающих.

-- Прости, мы просто уже успели перекинуться парой слов, пока ты дрых... 
Меня и Иви ты уже знаешь, это Эди, Дана, хотя вы похоже уже знакомы, судя по тому как прячете взгляды... 
Жажду подробностей... Ну а это...

-- Я сама могу представиться, Раян, -- перебила его темноволосая девушка задававшая за завтраком вопросы. -- 
Оливия.

-- Макс! -- он ответил рукопожатием на протянутую руку.

-- Думаю нам стоит поторапливаться. -- Иви уже успела разложить карту на земле. 
Та больше напоминала на рисунок из фентези игры, чем реальную карту. 
-- Судя по всему локация о которой шла речь находится вот здесь на юге.
-- Она показала на небольшой домик обведенный в красный кружок. 
-- Ну, а мы видимо вот здесь в центре на опушке. 
И если верить масштабу нас разделяет около 40 километров...

-- 8 часов в нормальном темпе, по лесу все 9, -- Раян глянув на таймер начал закидывать рюкзак себе на спину.
-- У нас есть чуть больше 11, как раз с обедом должны успеть. Выдвигаемся!
-- Дана и Эди тоже похватались за свои вещи.

-- И далеко собрался? -- Оливия едва сдерживала смех

-- Эм, за батарейками... -- Он развел руками не понимая подвоха.

-- Куда?

-- Иви вроде сказала, на юг...

-- А это в какой стороне?

-- Там, -- он резво развернулся на 180 градусов и показал прямо, но тут же резко одернул руку. -- Черт!

-- Да, есть проблемка! -- Иви тоже решила слегка подразнить парня. 
-- У кого-то в вещах был компас?

-- В телефоне должен быть, -- Макс выпалил это быстрее того, как успел осознать что именно смущало его все это время -- пустые карманы. -- Которые у нас похоже отобрали...

Большинство рефлекторно проверило собственные.

-- Компаса вроде ни у кого не помню. Идем искать мох? -- Раян пытался не сбавлять выбранный темп принятия решений.

-- Хотелось бы что-то чуть более надежное, -- Оливия видимо слегка разбиралась в ориентировании. 
-- Лучший ориентир это солнце, но часов у нас с собой видимо тоже нет.
Надо следить куда оно двигается, так что присаживайтесь, это займет время.

-- Которого у нас не много, -- Иви взглянула на циферблат, а потом вверх, где солнце только изредка выглядывало из-за туч и облаков, 
-- да и не факт, что через пол часа мы в целом сможем его увидеть.

-- Есть варианты лучше? -- В голосе Оливии прослеживалось легкое раздражение.

Макс подошел к карте, которая продолжала лежать на траве придавленная несколькими камнями. 
На западе и востоке тянулось два горных хребта между которыми они и находились. 
На север и юг, относительно узкой полосой, простирался лес через который им и предстояло идти к цели. 
Макс присмотрелся повнимательнее. На западе, между лесом и началом гор, текла река...

-- Я знаю, -- Иви опередила его буквально на мгновение. -- На западе у подножья есть река, на востоке - нет.
В оба направления идти около часа, разделимся, найдем реку - найдем юг.

-- Супер, -- почти хором выпалили Эди и Оливия.

-- Мы потеряем 2 часа, очень рискованно, -- наконец Макс услышал голос Даны.

-- Зато гарантировано будем знать куда идти! -- Иви не отступала.

-- Я не спорю, план не плох, но может у кого-то еще будут идеи? -- Дана обвела всех взглядом полным надежды.

Все молчали. Судя по взгляду думать пыталась только Дана, остальных вполне устраивал озвученный план.

-- Теряем время! -- Иви начала паковать карту в рюкзак, Дане ничего не оставалось, кроме как поджав губы молча согласиться. 
-- Разделимся на тройки. Я, Раян и... -- Она внимательно осмотрела оставшихся, выбирая кто ей больше по душе. -- Оливия!
Мы пойдем туда! -- Она указала на горы по направлению своего взгляда. -- Остальные в противоположном направлении.
Ориентировочно через 2 часа встречаемся на этом же месте.

-- Командовать видимо у них семейное. -- Пробурчала Дана подходя к Максу и Эди.