== Глава

-- Неужели не было варианта элегантнее? -- Дана все никак не унималась, пока они с Максом и Эди пробирались сквозь лес к горам.

-- Чем тебя этот не устраивает?

-- Тем что его придумала Иви?! -- Она произнесла это так, буд-то Макс должен был давно это понять.

-- Никогда не понимал, как женщины успевают так быстро поругаться, что вы уже не поделили? 

-- Во-первых это сексизм, а во-вторых мы не ругались, я исхожу из чистой выгоды.
Как ты думаешь, сколько победных очков дадут за эту идею?

-- То есть тобой руководствовала жадность, а не желания найти более быстрое решение? 

-- Мной руководствовало то, что Иви и Раян изначально в более выгодных условиях. 
Они пара, а значит могут действовать сообща, чтобы забрать денежный приз.

-- То есть таки жадность... -- Макс пытался подать это больше как шутку, но Дана воспринимала ситуацию в серьез.

-- Не знаю как вы, а я ехала сюда с целью победить, и я своего добьюсь. -- По ее интонации ей трудно было не поверить.
-- Но в сложившейся ситуации мне нужны будут союзники. Их двое и они вырвались вперед, но думаю втроем мы наверстаем упущенное.

Макс и Эди шли чуть впереди расчищаю дорогу и почти синхронно развернулись уставившись на Дану.

-- Что?.. Решения придумываем вместе, но озвучивает их кто-то... одна. Приз потом тоже делим на троих.

-- Утром ты боялась встретиться со мной взглядом, а теперь предлагаешь сделку?

-- Я адаптируюсь, -- она слегка улыбнулась. -- И не говори, что откажешь мне, потому что вчера я отказала тебе.
Может я отводила взгляд, потому что мне трудно было признать собственную ошибку?

-- Не уверен что твой сарказм приближает наш союз.

-- В каждом сарказме есть доля сарказма! А если серьезно, то подумай, опьяненная победой я буду куда более сговорчива...
-- Она игриво закусила губу.

"Интересная вырисовывается ситуация, второе место все привлекательнее и привлекательнее".

-- Ты задумался, так что расценю это как согласие. Эди, а ты что скажешь? 

-- Сейчас ты пытаешься обхитрить их, а потом попробуешь обхитрить меня. Знаем мы таких, обжигались. 
И глазки мне можешь не строить, ты не в моем вкусе. -- Он говорил все это с легкой ухмылкой глядя ей прямо в глаза.

-- Будешь потом локти кусать, Эди. -- Дана не собиралась проигрывать игру в гляделки.

-- Повторюсь, ты хитрая лиса, а я хорошо знаю чем заканчиваются истории с лисами.