== Глава

Такси медленно ползло по густо застроенному многоэтажками району. 
На улице моросил дождь и Макс удивился, когда подруга вызвалась встретить его у входа во двор:

-- Возле ворот, пожалуйста!

Лиза стояла под зонтом у входа в огражденную территорию жилого комплекса.

-- Домофон сломан, ты бы даже во двор сам не зашел, -- пояснила она. Макс нырнул под зонт и обнял ее в знак приветствия. 
–- Пойдем. Как твой день?

-- Если ты думала, что я отвечу нормально и мы перейдем к обсуждению того ради чего ты меня сюда вытащила, то ты ошиблась с формой приветствия.

-– Ууу, у кого-то не задался понедельник?

–- Я окончательно разочаровываюсь в этом мире... и, что самое главное, в себе. 

–- С чего же это ты вдруг? –- саркастично вырвалось у Лизы, но Макс не распознал риторичность вопроса и с серьезной миной продолжил.

–- Я занимаю одну из ключевых технических позиций в компании, от моих решений зависит качество продукта, эффективность процесса разработки и черт знает что еще. 
Каждый день я принимаю целую кучу таких решений, убеждаю своих коллег в надобности непопулярных изменений, короче играю очень важного дядьку. 
Но что если я зациклился? 
Что если не замечаю как параллельно с моими "гениальными" улучшениями происходит что-то, что угрожает существованию всего проекта, и как следствие компании?

–- Ну слушай... –- Лиза, явно не ожидавшая с порога таких серьезных тем, слегка замялась. 
–- Когда люди принимают решения у них всегда есть шанс ошибиться, не понимаю почему... 

–- Потому что, -- перебил ее Макс, — точно так же как я уверен в идеальности своего технического решения текущей проблемы, точно так же я был уверен в идеальности своего хода сегодня днем. 
Шахматы, —- добавил он, увидев взгляд искренне пытающийся уловить суть его слов. 
-— На доске у тебя есть вся картина мира, ты можешь просчитать последствия своих решений и даже тут я... мы... умудряемся допускать очевиднейшие ошибки, что уж говорить о реальной жизни в которой тебе приходится оперировать огромным количеством неопределенности.

-- Да, но ты просто человек... --- Лиза пыталась сделать как можно более спокойное лицо, но было заметно, что она не очень понимает, как реагировать на вышесказанное.

–- Может даже сейчас... –- не замечая собеседника, продолжал Макс. 
—- Может даже сейчас я зевнул королеву. Может ты тут готова была признаться мне в чувствах, а теперь услышав все это осознаешь, что оно того не стоит, —- закончил он с легкой улыбкой на лице, пытаясь чуть сбавить заданный собственнолично градус беседы.

–- Сочту это за комплимент, хотя слышала и получше – королева все таки вторичный персонаж в этой игре.

–- Ну да, ну да, кто-то даже предпочитает размен королев... –- вставил Макс уже расплываясь в улыбке.

–- Даже не сомневалась, что ты схохмишь. –- Лиза попыталась выразить отвращение к пошлости, но края губ ее все таки выдали. 
–- И тем не менее, может это не зевок, может это твоя жертва, дабы укрепить позицию в контексте выдвинутых идей.	

-– Думаешь я ради этого все тебе вывалил? 

-– Ну а зачем еще?

У Макса уже не было возможности ответить. 
Лиза открыла дверь квартиры и скользнула в кромешную темноту. 

-– Заходи, не стесняйся!

Он слегка замялся, тщательно вытер ноги и переступил порог.

–- Сююююрприиииз!

В гостиной тут же вспыхнул свет, раздались взрывы хлопушек, Макс инстинктивно заморгал от летевшего в его лицо конфетти. 
Придя в себя от неожиданности он разглядел толпу людей, по большей части состоящей из хорошо знакомых ему лиц, которые уже затягивали “Happy Birthday To You”. 
Лиза вышла из комнаты слева с конвертом привязанным к гелиевым шарам.

–- С прошедшим! -– сделав самое жизнерадостное лицо в мире выпалила она перекрикивая песню. Затем обняла Макса и добавила на ухо: –- С учетом нашего диалога с подарком мы угадали.

Макс взял конверт, все еще не до конца осознавая что происходит. 
Его лицо покраснело настолько, что он ощущал как пульсирует кровь в районе щек.
Песня-поздравление тем временем подошла к концу, и наступила неловкая тишина, прервать которую, по видимому, должен был он.

-– Хей, потеряшка... –- Лиза попробовала выдернуть Макса из внутренних раздумий, которых на самом деле не было.

–- Да-да, я... эм... –- дар речи все еще был в ограниченной доступности. 
-- Это очень... очень, – Макс попытался сделать акцент на этом слове, –- неожиданно и ...

–- Боже, да всуньте ему уже в руку пиво вместо этого бесполезного конверта, –- крикнул кто-то из толпы, чем вызвал всеобщее одобрение.

Парень стоявший ближе всего к Максу протянул ему бутылку.

–- Да, так пожалуй будет лучше, только ты забыл уточнить чтобы ее открыли, –- саркастично пробормотал именинник вызвав поодинокие смешки. 
-– Но ничего, так тоже сойдет, –- и приложил прохладную бутылку ко лбу. 
–- Как видите, я... впечатлен до глубины души и... короче, пиво за мой счет, а там дальше разберемся.

Толпа выдала очередной одобрительный гул, кто-то включил музыку, приглушил свет и народ пританцовывая начал разбредаться по углам большой гостинной.

-– Решила что с тебя хватит, -– прокричала Лиза убирая руку от переключателя. 
-– И если ты думаешь что я не выставлю тебе счет за пиво, то ты глубоко заблуждаешься.

Заиграла “Send Me An Angle” и Макс жестом пригласил ее на танец.

–- Ого, и куда же делась все твоя застенчивость?

–- Ну не зря же мне вручали пиво, –- теперь они могли слышать друг друга не надрывая горло. 
-– Ты же знала, что я не хочу праздновать, –- немного подумав выдавил Макс.

–- Знала, но... 
Родители в коем веке свалили отдыхать оставив мне квартиру в полное распоряжение, и я решила устроить вечеринку, -– она оглядела комнату. 
-– Потом подумала, почему бы не совместить? Да и что-то я не заметила разочарования на твоем лице.

–- Не говори гоп, вечер только начинается. –- Его глаз зацепился за парящий в воздухе конверт. 
–- Что в нем?

–- Не скажу из вредности, открой и посмотри, -– Лиза сделала слегка обиженное лицо и удалилась на кухню.

Макс еще какое-то время смотрел ей вслед пытаясь что-то съязвить, но так ничего и не придумав побрел к подарку, по пути наконец-то поздоровавшись с частью присутствующих. 
С некоторыми пришлось знакомиться. У них с Лизой было много общих знакомых, но сегодняшние сборы она видимо действительно затевала как просто вечеринку для всех.
В конверте оказался билет, в виде деревянной дощечки с выжженным текстом, на какой-то многодневный квест в горной местности. 
Макс развернул прилагавшийся буклет с описанием, слегка оперся на стену и углубился в изучение деталей.

–- Минуточку внимания! –- музыку приглушили и какой-то высокий темноволосый парень, подняв повыше свою бутылку с пивом, созывал всех поближе. 
Макс хотел его полностью проигнорировать, так как как раз добрался до описания места проведения, но затем обратил внимание на стоящую рядом девушку.

–- Не в обиду нашему имениннику, –- он сделал жест в сторону Макса, –- но это не единственное, что мы сегодня можем отметить. 
Мы еще никому не рассказывали, но думаю пора. –- Он посмотрел на стоящую рядом девушку полной от счастья улыбкой, ищя в ее взгляде одобрения. Та не очень уверенно улыбнулась в ответ.

–- Ох, только не это, -– пробубнел себе под нос Макс. Он обвел взглядом присутствующих. Лиза, как оказалась, занималась тем же, только с гораздо более обеспокоенным лицом. Встретившись с ним взглядом она слегка пожала плечами, показывая, что этого в ее планах не было.

–- Как вы знаете, –- продолжил парень, –- мы с Кэт давно работаем над одним проектом, –- он сделал глоток, пытаясь выдержать паузу, –- и месяц назад нам предложили примкнуть к более глобальной программе. -- Еще глоток. Он видимо ожидал реакции, которой не последовало. -- В Штатах.

На этот раз послышались приветствия и перешептывания, но Макс этого всего уже не слышал. 
Он скользнул в приоткрытую кухонную дверь и направился на балкон. 
В груди было неприятное щекотливое чувство слегка затрудняющее дыхание.

На балконе курил Игорь. 
Они познакомились несколько месяцев назад при довольно печальных обстоятельствах и с того момента не виделись, но Макс был наслышан о нем из рассказов Лизы, которая, по видимому, изрядно на того запала.

–- Есть сигарета?

–- Ты вроде не курил, –- констатировал Игорь. –- Плохой день?

–- The most loneliest day of my life, –- процитировал Макс загадочно улыбаясь.

–- It's a day that I'm glad you survived, -- последовало в ответ. 

Такая внезапная коллаборация рассмешила обоих. 
Макс затянулся предоставленной сигаретой, оперся на подоконник и стал ловить лицом капли дождя изредка залетающие в открытое окно. 
Но это мало чем помогло, в голове творился какой-то хаос из мыслей, как будто кто-то ссыпал полностью собранный пазл обратно в коробку. 

–- Я вот тебе даже завидую, –- выпуская очередную порцию дыма нарушил молчание Макс. 
Игорь недоумевающе взглянул на него. 
-– Ты ведь в похожей ситуации, только тебе не приходится периодически наблюдать результаты своих ошибок.

–- По аккуратнее с выражениями, –- огрызнулся Игорь начиная понимать смысл слов собеседника. –- Ты не знаешь о чем говоришь.

–- Нет, ну серьезно, ты можешь обвинить в произошедшем кого угодно, только не себя.

–- Макс... -– последовал предупреждающий крик.

–- Тебе не нужно бороться с самобичеванием, ты...

Игорь не дал ему договорить. 
Удар прошел чуть вскользь, но силы хватило чтобы Макс потерял равновесие и ударившись спиной о дверцу шкафчика сполз на пол.

-- Я готов терпеть угрызения совести до конца своих дней, лишь бы она была жива. 
-– В глазах Игоря было столько ярости, что Максу казалось тот готов его убить. 
-– Ты понятия не имеешь насколько это больно.

–- Чем твоя боль отличается от моей?

–- Ты издеваешься?

–- Мы оба потеряли любимых женщин, с чего ты вдруг взял, что твоя утрата больнее?

–- Твоя... утрата, –- он выговорил это слово с максимальным отвращением, –- стоит в соседней комнате, а моя... 
-– Ком подобравшийся к горлу не дал Игорю закончить. 
Нахлынувшая душевная боль постепенно вытеснила злость, что спасло Макса от новых увечий. 
-– Не я начал тут меряться кому из нас хуже. Идиот.

Бросив эти слова Игорь удалился с балкона разминувшись в дверях с прибежавшей на крик Лизой. 
Ее ужаснул взгляд возлюбленного, но окровавленное лицо Макса произвело большее впечатление и она кинулась помочь ему встать.
Падая от удара он напоролся спиной на ручку дверцы и теперь она саднила заставляя прихрамывать и не давая вздохнуть полной грудью. 

–- Что, черт возьми, у вас тут произошло? -– наконец спросила Лиза, запихивая ему в нос кусок ваты.

-– Музыкальные вкусы не сошлись.

–- Я сейчас тебе добавлю, шутник.

-– О, кто-то уже разговаривает как мамочка.

Лиза сделала шаг назад.

–- Макс... Тебе только что, скорей всего, за такие же язвительные фразочки разбили нос, а ты как ни в чем не бывало продолжаешь?

–- Да задел я твоего Игоря за живое, задел, –- в его голосе начало прорезаться раскаяние.

Лиза тут же изменилась в лице, пытаясь сделать вид, что между ними ничего нет.
Макс закатил глаза:

–- Ты мне все уши про него прожужжала, думаешь я не догадался?

Она села рядом с ним на стул и повесила голову:

–- Он все еще ее любит?

–- Прошло всего полгода... -- Макс приобнял ее за плечи. 
-- Да и не думаю что тебе стоит ждать когда разлюбит. Лучше помоги ему об это не думать.

-– Как? -- ее голос переполняло отчаяние.

–- Ну, например, не приглашай в гости людей которые ему о ней напомнят, –- Макс попытался улыбнуться, но тут же пожалел об этом, скорчившись от боли.

-– Ты неисправим, –- вздохнула она и протягивая билет добавила: 
–- Держи, обронил когда падал. 
Думаю после всего что произошло тебе точно нужно поехать отдохнуть, а то нос с каждым ударом ровнее не становится.

Лиза ушла в гостиную, а Макс еще долго сидел уставившись в одну точку, постукивая подарком по столу.










