== Глава

Пронизливий звук заповнив занурену в напівтемряву кімнату. Макс метушливо намагався намацати джерело роздратування, жбурляючи руку на тумбочку біля ліжка. 
Нарешті долоня натрапила на щось подібне на стаціонарний телефон.

-- Доброго ранку! Ви просили розбудити вас перед сніданком. О 8 годині на вас будуть очікувати в барі на другому поверсі.

-- Дякую – хриплим голосом промовив Макс в трубку, що вже видавала короткі гудки.

Протираючи очі, він нарешті почав пригадувати, де саме він знаходиться. За вікном на горизонті розкинувся гірський хребет, за яким повільно з'являвся вогняний круг сонця. 
Готель, в який він прибув напередодні вечером також знаходився на височині, і ослаблений від дороги Макс надав перевагу завершити цей день в барі замість розвідувальної прогулянки околицями. 
Там він зустрів декількох однодумців і зараз відчував наслідки плідного спілкування, такі як шум в голові та легку нудоту.

Бар на другому поверсі являв собою вузьке приміщення з довжилежною барною стійкою і декількома столиками вздовж протилежної стіни, які до моменти приходу Макса були вже зайняті. 
З присутніх він впізнав тільки одну світловолосу дівчину, яка спрбувала уникнути зустрічі поглядів, тож Макс вирішив присісти за сусідній стіл до молодої пари.

-- Вільно?

Хлопець схвально кивнув і продовжив поглинати свій біфштекс, а дівчина з легкою посмішкою продовжувала дивитись на Макса весь час, поки він всаджувався за столом, і не сильно зніяковіла від зустрічі їхніх поглядів. «Ніколи не розумів, як сприймати такі затяжні споглядання від зайнятих жінок», подумав він про себе і про всяк випадок поправив зачіску.

-- Я Іві, а це Раян, -- дуже енергійно випалила нова сусідка по столику.

-- Дуже приємно! Макс!

-- Ви теж братимете участь в квесті? -- не зменшуючи ентузіазму продовжила Іві.

-- Так, і я так розумію тут збір всіх учасників, -- Макс обвів поглядом присутніх.

-- А я от думаю, що він вже почався...

"Архімед був явно менш натхненним своїми відкриттями", проскочило в голові Макса, побачивши палаючі очі співрозмовниці.

-- Ось, погляньте на їхнє меню, -- вона вказала на назву страв, виконаних у вигляді ребусів з малюнків, дуже схожих на єгипетські ієрогліфи. 
-- Раян насправді думав, що замовляє біфстроганов, але здається ми щось наплутали, -- радість на її обличчі змінилась награним сумом.

-- Головне, що тут є м'ясо, -- прокоментував басовитим голосом хлопець, на секунду відірвавшись від страви.

В цей момент вхідні двері злегка скрипнули, чим привернули до себе увагу всіх присутніх. 
В приміщення впевненим кроком зайшла жінка в строгому діловому костюмі. 
За нею спішно дріботів чоловік у віці, а закривала процесію молода дівчина в білому лікарському халаті. 

-- Мої вітання всім! -- жінка зайшла за барну стійку та сперлась на неї руками. 
-- Мене звуть місіс Олді і я відповідаю за те, щоб ви отримали максимальну якість послуг під час даного заходу.

ЇЇ командний голос викликав у Макса відчуття, ніби вони сидять в окопі, а не в барі, і командир ось-ось відправить їх на штурм ворожої позиції.

-- Зазвичай я надаю перевагу особистому знайомству з нашими гостями, втім вчора, на жаль, були  непередбачувані обставини, -- тим часом місіс Олді продовжувала карбувати слова. --
ле думаю ми з вами ще встигнемо надолужити згаяне, а поки я хотіла б швидко нагадати основні правила та дати декілька рекомендацій. 
Перше -- хоч переможець в нашому квесті тільки один, без командної роботи вам його пройти не вдасться...

-- Ми точно не в армію попали? -- рошепотів Макс сусідам за столиком. Вони обоє знизали плечима, даючи зрозуміти, що тон ораторки не викликає інших асоціацій.

-- Друге -- більшість випробувань, які вам доведеться подолати пов'язані з певними фізичними навантаженнями, тому ми просимо вас пройти мінімальний медогляд. 
З цим нам люб'язно погодилась допомогти міс Тернер, -- вона вказала рукою на дівчину, що зайшла з нею. 
-- Якщо у вас є якісь недуги чи побажання, ми обов'язково постараємось їх взяти до уваги.

-- А що, якщо в когось з нас несумісні протипоказання? -- прозвучало з сусіднього столика.
-- Відправите нас додому? Чому не можна було це зробити до нашого приїзду сюди?

Місіс Олді декілька секунд сверлила поглядом дівчину, що осмілилась її перебити, втім, добавивши ще більшої жорсткості своєму голосу, все ж відповіла:

-- Міс Бартон, як я  вже зазначала, ми врахуємо особливості кожного з вас. 
Наступного тижня я особисто відповідаю за вашу безпеку і хочу бути впевненою в достовірності інформації про стан вашого здоров'я. 
Всі ви достатньо юні, маєте по 2 руки та ноги, все решту -- вирішується. -- Вона знову зробила паузу і обвела кожного лютим поглядом, даючи зрозуміти, що подальші питання зайві.

-- Третє -- протягом всього квесту ведеться відеозапис того, що відбувається та матеріали передаються в наш місцевий інститут психологїї та соціології, -- цього разу рукою вона вказала на чоловіка, що стояв поруч. Той, злегка вклонився в знак вітання.

-- Перепрошую, але я не давав згоду бути підослідним кроликом, -- звернувся до неї Раян, відчутно підвищивши тон.

Хлопець, що сидів за дальнім столиком в окулярах та із зализаною зачіскою, пирхнув і закотив очі.

-- Боюсь вас засмутити, містер Стівенсон, але давали, -- вперше з початку розмови, на обличчі місіс Олді з'явилась усмішка.
-- Цей пункт був вказаний в нашій згоді користувача, яку ви підписуєте під час придбання сертифікату для участі.

-- ак і від нирки можна відмовитись, -- єхидно прокоментував хлопець в окулярах.

"Або за тебе це зроблять твої друзі...". 

-- Дуже розумний? -- Раян злегка припіднявся над столом. Макс теж трохи відсунувся, готуючись рознімати цю парочку. 
-- По тобі помітно, що крім вичитування папірців  тебе в цьому житті більше нічого не цікавить...

-- Панове! -- цього разу місіс Олді довелось перейти на крик. -- Прошу з повагою ставитись один до одного. 

-- Милий, заспокійся, не бачу нічого жахливого в тому, що нас буду знімати  на камеру, -- Іві взяла його за руку і постаралась встадити назад. -- Ми ж зможемо потім отримати ці відео на пам'ять? 

Місіс Олді переглянулась з іншими представниками інституту.

-- Якщо ніхто з учасників не буде проти — думаю ми зможемо таке організувати. Містер Стівенсон, ми гарантуємо максимальний захист даних, які зберігає інститут, а також запевняю вас, що процес зйомки ніяк не відобразиться на якості вашого відпочинку.

Раяну явно було байдуже на озвучені пояснення, втім, під благальним поглядом Іві він все ж сів та постарався заспокоїтись.

-- Також хочу добавити, що саме співпраця з інститутом дозволяє нам організовувати для учасників винагороду за перемогу.

-- Тут є приз?! -- цього разу здивування вже охопило Макса, але озвучив він його тільки пошепки для Іві та Раяна.

-- Звісно, 10 тис доларів! Я думала більшість тільки заради цього сюди й приїхали, -- Іві була не менш здивована питанням Макса, аніж він сам наявністю винагороди. 

-- Четверте, -- продовжила місіс Одрі, оцінюючи Макса поглядом, -- й останнє.
Приз забере той, хто набере найбільше балів, втім, тільки в випадку виконання всіх завдань. 
А для цього, нагадаю, потрібно діяти, як команда. Чим більше користі ви принесете, тим більше балів отримаєте. 
Як саме ми будемо їх начислювати, ми звісно ж вам не розкажемо, імпровізуйте! -- На її обличчі з'явилась єхидна посмішка
-- Бажаю вам успіху і сподіваюсь наступні декілька днів стануть найнезабутнішими у вашому житті.

Хлопець в окулярах зааплодував, втім зупинився, відчувши на собі дивні погляди замість підтримки.

-- Міс Тернер  чекатиме в 103-ій кімнаті, -- промовила наостанок місіс Олді, виходячи з бару.


