== Глава

Кімната №103 була звичайним готельним номером, переробленим під медпункт, Білосніжно-білі стіни, меблі, обладнання та халат на міс Тернер. 
Була б вона не такою засмаглою, цілком могла б позмагатись з хамелеоном.

-- Максим?

-- Так-так, -- злегка почервонів Макс від розуміння, що просто мовчки дивився на медсестру з моменту, як увійшов.
-- Перепрошую... подумав, що помер, коли попав в цю кімнату.

-- Роздягайтесь по пояс і лягайте на лежанку, -- она залишила його слова без уваги і почала підключати електроди для зняття ЕКГ. Зробивши виміри, вона попросила Макса присісти 20 разів і знову повторила процедуру. -- Задовільно. 

Наступні декілька хвилин вона вносила дані в комп'ютер, певно даючи Максу час остаточно прийти до себе після присідань. 
Наступним етапом був стетоскоп, дотик якого до місця удару змусив Макса здригнутися.

-- Давно це у вас з лопаткою? 

-- Вже більше тижня, щось серйозне? 

-- Не думаю, але... -- вона з посмішкою глянула йому в очі, повертаючись за стіл, -- обіцяти, що живе до весілля - не наважусь. 

Макс на мить втратив здатність дихати. “Ох міс Тернер, здається саме час повторити ЕКГ...
Чорт побери, Макс, тобі б відповідь придумувати, а не монологи в голові влаштовувати. 
Відповідь-то є, втім чи варто її озвучувати? Можливо це тільки прохолодний жарт...”

-- На щось натякаєте? 

"Краще б про ЕКГ сказав...".

-- Хах, нуу...вийти заміж в цій кімнаті мені ще не пропонували! -- її посмішка стала трохи ширшою.

-- А що пропонували?

"А це що таке було?.."

-- Ви справді хочете знати? -- вона зиркнула на кушетку, втім спершу Макс встиг зловити здивування на її обличчі.

"А що я, власне, очікував почути у відповідь?.."

-- Ні, як і не хочу кликати вас заміж... Втім, був би не проти відкоркувати з вами пляшечку… до речі якого? 

-- "Відкоркувати" -- вона голосно розсміялась. -- А ви виявляється зухвалий аристократ... Боюсь, змушена вам відмовити, я не маю права заводити відносини з клієнтами фірми. 

"А навіщо тоді всі ці милі посмішки та дивні вислови?.."

-- Добре, давайте опісля.

Міс Тернер опустила очі вниз, а потім сумно глянула на Макса:

-- Все ще ні.

-- І навіть відмовитесь від вечері з переможцем? -- Наполегливість заставила її знову посміхнутись.

-- А чи не забагато дістанеться переможцю? І грошовий приз, і вечеря зі мною? 

-- Добре, будете втішним призом для другого місця! -- Максу здалось, що він вже не може перестати штампувати варіанти, інакше його мозок просто згорить від кількості кисню, що вкидає серце. 

-- Це... злегка образливо...

-- Аж ніяк, в поставлених умовах зайняти друге місце куди складніше завдання, ніж перемогти. 
Ми не знаємо точних правил начислення балів, тобто потрібно не просто в усьому бути кращим. 
Потрібно зрозуміти критерії організаторів, постійно оцінювати за ними, хто саме перемагає, і бути на крок позаду. 
Куди більше мороки, не здається так?

-- І ви дійсно готові витратити більше зусиль, щоб отримати не 10 тис, а вечерю зі мною? Це лише вечеря, я нічого більше не обіцяю. 
А навіть, якби обіцяла, в сучасному світі за цю суму можна отримати значно більше задоволення.

"Саме тому я і назвав цей приз втішним..."

-- Я їхав сюди навіть не підозрюючи про приз за перемогу, тож можна сказати, я нічого не втрачаю.

-- Боюсь про мене ви теж не підозрювали, тож не зараховано.

"А ти хороша..."

...

-- Так і не дізнався, як вас звати? -- відкриваючи двері запитав Макс.

-- Сегунда.

-- Здається "Королева шипів" підійшло б краще... -- похитуючи головою і посміхаючись він вийшов у коридор.
