== Глава

Макс прокинувся від того, що хтось тряс його за плечі. Він привідкрив очі, але відразу ж заплющив їх від яскравого сонячного світла. 
Примружившись, йому вдалось розгледів напружене обличчя Браяна на фоні синього неба, на горизонті вдалині з усіх боків виднілися гори, від яких його відділяв густий ліс. 
Трохи прийшовши до тями, Макс помітив всіх тих, кого бачив учора на сніданку. "Чи вчора?"

-- Де ми? -- похрипів він усе ще сонним голосом, відчайдушно стараючись згадати, де він засинав. 
-- І що за хрінь у тебе на руці? 

-- Не одного тебе хвилюють ці питання. -- єхидно всміхнулась Іві, кивком голови вказуючи на руку Макса.

Він повільно опустив очі на ліве зап'ястя і побачив там масивний залізний браслет, що щільно облягав руку. 
Макс злегка повернув передпліччя, і його очі натрапили на невеликий циферблат, який відраховував час: "23:47:19". 
Він машинально спробував зняти його, але Браян схопив його праву руку. 

-- Я вже пробував, тільки гірше зробиш.

-- Ну що ж, початок вражає...

