== Глава

Макс долго сидел в своем кресле, откинувшись на спинку, и внимательно изучал потолок. 
Правда "изучал" не совсем подходящее слово, скорей - повторял материал.

-- А говорят вечно можно смотреть только на 3 вещи.

Коллега заставил Макса оторвать взгляд от поглощающей белизны. 

-- Ты же не знаешь, что я там вижу...

-- И не уверен, что хочу. Мы собираемся на обед, ты как?

"Вот и еще один повод ненадолго отложить работу...  
Нет,  так дело не пойдет,  может получится хотя бы голодом себя мотивировать".

-- Я позже пойду, спасибо!

Макс перевел взгляд на монитор, открыл проектную документацию, положил кончики своих пальцев на клавиатуру и... 
Ничего... 
Теперь таким же безразличным взглядом, как и минутой ранее, он всматривался сквозь белый текст в темный фон текстового редактора, а кончики его указательных пальцев нервно поглаживали едва заметные выступы на клавишах "А" и "О". 
Решение рабочей задачи, продуманное до мелочей, уже несколько дней существовало в голове Макса. 
Оно нравилось ему, было достаточно элегантным, хорошо укладывалось в существующую структуру, можно даже сказать слишком хорошо, что вызывало некоторую настороженность. 
Но мозг Макса на отрез отказывался отдавать команды телу, чтобы материализовать это решение. 
Он как будто боялся, что увидев его глазами поймет, что не такое уж оно и красивое.

В голове Макса проскользнули аналогии с его последними любовными похождениями. 
Вот он знакомится на вечеринке с симпатичной девушкой, с которой у него так много общего, и кажется, что с ней можно говорить вечность.
Его логическое и критическое мышление еле успевают спрятаться в бункере от бомбардировки гормонами "любви".
Оставшиеся на посту отделы мозга присваивают этой девушке недостающие идеальные черты и вот наш герой, полный решимости и сладостного предвкушения, уже мчится на второе свидание. 
Но протрезвевший, от гормонального коктейля, с первых минут начинает замечать, что все это "общее" что между вами есть, можно найти почти в любом человеке на Земле, что вне этого "общего" нет почти ничего, что было бы хоть сколько-то ему интересно. 
Нет, она все еще очень красива и притягательна, но в этот раз критическое мышление возьмет реванш...

Раздосадованный нахлынувшими воспоминаниями Макс взглянул на часы: 12:47. 
"Отлично, как раз есть время сыграть быструю партию в шахматы и в 13:00 приняться за работу. 
Главное успеть закончить до 13, а то придется опять ждать до 14. Работник месяца...".

Несмотря на укоры совести он все таки открыл приложение на телефоне и начал дожидаться соперника. 
Ахтар из Индии, хоть и имел более высокий рейтинг, ничего необычного в дебюте не продемонстрировал и Максу казалось, что он оказался в более выгодной позиции. 
Его глаза бегали по доске повторяя траекторию ходов, которые Макс просчитывал в поисках выигрышной комбинации. 
Это не было похоже на методичный перебор всех вариантов, возможные ходы возникали в голове из ниоткуда и оставалось лишь просчитать к чему они ведут. 
Углубившись в один из вариантов, и убедившись что он даст материальный перевес, Макс скакнул своим конем в самую гущу событий на королевском фланге. 
Индус ответил незамедлительно переводом ферзя на одно из центральных полей оставленное без присмотра того самого коня. 
Макс опешил... 
Он абсолютно упустил из виду такой вариант развития событий и осознал, что ход конем открыл возможность для атаки его короля, что повлечет за собой куда большие потери, чем тот перевес, которым он собирался завладеть. 
Теперь, чтобы минимизировать потери, нужно было действовать очень точно, но на таймере оставалось слишком мало времени для тщательного продумывания ходов. 
Внутри Макса взыграла обида и злость на себя. 
Он тут же сдался и отрицательно качая головой снова уставился в потолок, не понимая, как он мог так ошибиться.

На сей раз телефон оторвал Макса от его раздумий, напомнив о предстоящем совещании. 
Он лениво надел на себя наушники с микрофоном и погрузился в дискуссию касательно технических решений по второму проекту.
Дискуссию, которая по его мнению в принципе не должна была возникнуть, будь в составе команды достаточно компетентный человек. 
Дискуссию, которая превращала хорошо структурированное решение, обладающее одним очевидным изъяном осложняющим жизнь ряду коллег, в непонятное чудовище семейства Франкенштейнов, в котором никто никогда не найдет изъяна, просто потому что ни у кого никогда не хватит смелости смотреть на него так долго. 
Хотя нет, вот же они изъяны, все их прекрасно видят, но технари уже устали спорить, менеджеры кричат о горящих сроках, а автор исходного решения уже мысленно на приеме у своего психотерапевта.

Не став дослушивать окончания фразы: "Принимаем в текущем виде,  исправления текущих недостатков запланируем...", Макс отключился.

-- Кого вы предпочтете, красивую девушку без правой руки, или не очень красивую  без левой? —- спросил он у сидящих в кабинете коллег.

На него установилось несколько пар глаз ждущих продолжения монолога.

-- На первый взгляд ответ очевиден, но большинство вещей в этом мире создано именно для правшей, и с левшой вам будет сложнее...

-- Звучит не очень убедительно! -- вырвалось у кого-то.

-- Для тебя, для меня, но не для отдела маркетинга, который, ко всему прочему, так лучше сможет показать, что мы выбираем женщин не за внешность, -- эмоции начали переполнять Макса. 
—- Хотя сами для брошюры выберут красивую, еще и обрежут так, чтобы отсутствующей руки не было видно...
Они обрежут отрезанную руку... —- подытожил он, подбирая паузы и интонации так, что могло показаться будто он на сцене стендап шоу, а не за рабочим местом.

Никто ему так и не ответил. 
Кто-то молча согласился, кто-то посчитал черный юмор не очень уместным, в любом случае настало время возвращаться к работе. 
Как только он перевел взгляд на монитор, то тут же опять завибрировал телефон. 
"Ух, какая жалость…". 
От неожиданности у Макса приподнялись брови, на экране всплыло сообщение от подруги:

[.msg]
Привет, сможешь заехать вечером?