== Глава

Пронизывающий звук наполнил комнату погруженную в полумрак.
Макс лихорадочно пытался нащупать источник раздражения роняя руку на прикроватную тумбочку.
Наконец ладонь встретилась с чем-то похожим на стационарный телефон.

-- Доброе утро! Вы просили разбудить вас перед завтраком, в 8 вас будут ждать в кафе на втором этаже.

-- Спасибо! -- прохрипел Макс в трубку издающую короткие гудки. 

Протирая глаза он наконец начинал вспоминать где находится. За окном на горизонте раскинулся горный хребет
из-за которого начал слегка проявляться огненный круг солнца. Отель, в который он прибыл накануне вечером, 
так же находился на возвышенности, так что ослабший от дороги Макс предпочел закончить уходящий день в баре 
вместо разведывательной прогулки по окрестностям. Там он встретил несколько единомышленников и сейчас ощущал 
последствия продуктивного общения в виде шума в голове и легкой тошноты.

Кафе на втором этаже оказалось рассчитано всего на 4 столика, которые, к приходу Макса, были уже заняты.
Из присутствующих он узнал только одну светловолосую девушку с бара, которая попыталась избежать встречи 
взглядов, так что Макс решил присесть за стол к молодой паре.

-- Можно? 

Парень одобрительно кивнул и продолжил поглощать свой бифштекс, а девушка с легкой улыбкой продолжала 
смотреть на Макса все время что он усаживался за стол, и не особо смутилась при встрече взглядов.
"Никогда не понимал, как воспринимать такие затяжные созерцания от занятых женщин", подумал он про себя и на 
всякий случай поправил прическу.

-- Вы тоже будете участвовать в квесте? -- решил прервать молчание Макс.

Парень опять одобрительно кивнул не отвлекаясь от блюда. 

-- Дааа! -- протянула девушка сменив улыбку на удивление. 
-- Думаете нас специально собрали в этой комнате?

-- В описании было сказано про 6 участников... -- Макс обвел взглядом всех присутствующих.

-- Думаете официант тоже с нами? -- спросила она слегка хихикая.

-- Нет, но от компании вот этой дамы я очень даже не откажусь. -- Макс взглядом указал на невысокую стройную брюнетку зашедшую 
в кафе. Собеседница слегка закатила глаза и стукнула по локтю своего парня, который тоже проводил девушку взглядом.




