== Глава

Макс зашел в ослепительно белый кабинет и слегка приподнял брови увидев сидевшую за столом девушку в белом халате.
Она слегка ему улыбнулась и пригласила к кушетке.

-- Раздевайтесь по пояс, -- она явно не собиралась терять время, потому в процессе Максу пришлось рассказывать 
краткие сведения о себе и жалобы на здоровья.

Закончив вводить данные врач подошла ближе к Максу. От запаха духов он слегка прикрыл глаза,
но прикосновение холодного стетоскопа быстро отрезвило. 

-- Волнуетесь? -- Макс и в правду осознал, что его сердце дико колотится. 

-- Возможно... 

При прослушивании спины Макс то и дело вздрагивал.

-- Что с лопаткой?

-- Даа... упал не удачно, -- Макс не нашел более интересного ответ, чем правда. 
-- Что-то серьезное? 

-- Не думаю, но в вашем случае обещать, что до свадьбы заживет, не стану. 

Сердце забилось еще быстрее, и ему в такт в голове постукивала мартышка с тарелками не давай придумать достойный ответ.

-- Чтобы такое случилось вам прийдется за меня выйти, -- таки выдавил он. Девушка слегка хихикнула.

-- Хах, замуж в этом кабинете меня еще не звали.

-- Но перед тем как вы скажите да, я бы все же предложил чуть ближе познакомится за бакальчиком... какого?
-- Макс сам удивился проснувшейся уверенности и дерзкости.

-- По уставу запрещено заводить отношения с клиентами, -- отрезала врач.

-- Мы можем подождать завершения сего действия...

-- Максим, я польщена, но... -- перебила она.

-- Неужели вам не интересно поближе узнать победителя? -- Макс всячески пытался скрыть удивление от того, что сам говорил.

-- Не много ли чести для победителя: и приз и ужин со мной? -- На лице девушке снова появилась легкая улыбка.

-- А роль утешительного приза за второе место вас больше устроит? 

-- А если я скажу да, сдадитесь в финале? 

Макс на секунду замешкался с ответом и этого хватило чтобы увидеть в глаза собеседницы, что эту словесную перестрелку он проиграл. Дальше наступила тишина. Она долго что-то искала в шкафу, наконец вернулась за стол с небольшой белой коробочкой.

-- В целом противопоказаний у вас нет, но спина при нагрузках будет болеть. Будете утром мазать.
-- Макс кивнул головой.
-- Пригласите следующего.

Почти открыв дверь Макс резко обернулся:

-- Зачем было шутить про "до свадьбы не заживет", если не собирались принимать приглашение на свидание?

-- Скучно! -- Ответила она пожимая плечами.

Отвратительное чувство разочарования после мгновения эйфории почти парализовало Макса.
Он добрался до своего номера, завалился в кровать и надолго уставился в потолок.